"""add split payments and tips to tabs

Revision ID: 0d00d74c24e9
Revises: c2cc15e4883f
Create Date: 2026-08-12 00:47:13.565764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d00d74c24e9'
down_revision: Union[str, Sequence[str], None] = 'c2cc15e4883f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('amount_cop', sa.Integer(), nullable=False),
    sa.Column('tip_cop', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['tab_payment_methods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_payment_item_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_payment_id', sa.Integer(), nullable=False),
    sa.Column('tab_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tab_item_id'], ['tab_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tab_payment_id'], ['tab_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tabs_payment_method_id_fkey'), 'tabs', type_='foreignkey')
    op.drop_column('tabs', 'payment_method_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tabs_payment_method_id_fkey'), 'tabs', 'tab_payment_methods', ['payment_method_id'], ['id'], ondelete='RESTRICT')
    op.drop_table('tab_payment_item_allocations')
    op.drop_table('tab_payments')
    # ### end Alembic commands ###
