"""add employees table

Revision ID: 15733bfceaa9
Revises: 96b6401f32e3
Create Date: 2026-08-05 22:53:33.361278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15733bfceaa9'
down_revision: Union[str, Sequence[str], None] = '96b6401f32e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('eps', sa.String(length=100), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=False),
    sa.Column('salario_mensual', sa.Integer(), nullable=True),
    sa.Column('salario_por_hora', sa.Integer(), nullable=True),
    sa.Column('arl', sa.String(length=100), nullable=True),
    sa.Column('fondo_pension', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=20), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=30), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
