"""add cash_sessions table and tabs.cash_session_id

Revision ID: 603826e797c5
Revises: 31629331fa6a
Create Date: 2026-08-11 19:11:41.652566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603826e797c5'
down_revision: Union[str, Sequence[str], None] = '31629331fa6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_by', sa.String(length=150), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tabs', sa.Column('cash_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_tabs_cash_session_id_cash_sessions', 'tabs', 'cash_sessions', ['cash_session_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tabs_cash_session_id_cash_sessions', 'tabs', type_='foreignkey')
    op.drop_column('tabs', 'cash_session_id')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
