"""add kind to tables

Revision ID: c2cc15e4883f
Revises: d7baaa7a1b3e
Create Date: 2026-08-12 00:11:42.551630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cc15e4883f'
down_revision: Union[str, Sequence[str], None] = 'd7baaa7a1b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tables',
        sa.Column('kind', sa.String(length=20), nullable=False, server_default='table'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'kind')
    # ### end Alembic commands ###
