"""add tables and extend tabs for account types

Revision ID: d7baaa7a1b3e
Revises: 2093e95825ea
Create Date: 2026-08-11 23:46:25.227921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7baaa7a1b3e'
down_revision: Union[str, Sequence[str], None] = '2093e95825ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('shape', sa.String(length=10), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tab_items', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column(
        'tabs',
        sa.Column('account_type', sa.String(length=20), nullable=False, server_default='dine_in'),
    )
    op.add_column('tabs', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tabs', 'tables', ['table_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tabs', 'table_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('table_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tabs', type_='foreignkey')
    op.drop_column('tabs', 'table_id')
    op.drop_column('tabs', 'account_type')
    op.drop_column('tab_items', 'description')
    op.drop_table('tables')
    # ### end Alembic commands ###
