services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-${APP_ENV}
    command: ${KC_COMMAND}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KC_DB_HOST}:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KC_PORT}:8080"
    restart: unless-stopped
    networks:
      - vca-net

networks:
  vca-net:
    driver: bridge