services:
  app-db:
    image: postgres:16.14
    container_name: app-db-${APP_ENV}
    profiles:
      - dev
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vca-net

  keycloak-db:
    image: postgres:16.14
    container_name: keycloak-db-${APP_ENV}
    profiles:
      - dev
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "${KC_DB_PORT}:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vca-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-${APP_ENV}
    command: ${KC_COMMAND}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KC_DB_HOST}:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KC_PORT}:8080"
    restart: unless-stopped
    networks:
      - vca-net

networks:
  vca-net:
    driver: bridge

volumes:
  app-db-data:
  keycloak-db-data: